core/urls.py
from django.conf.urls import url
from core import views

urlpatterns = [
    url(r'produtos/$', views.produtos, name='product_list'),
    url(r'produtos/save/$', views.produto_save, name='save_produto'),
    url(r'produtos/update/(?P<pk>\d+)/$', views.produto_update, name='update_produto'),
    url(r'produtos/delete/(?P<pk>\d+)/$', views.produto_delete, name='delete_produto'),

    url(r'clientes/$',views.contrato_client_list, name='contato_cliente_list'),
]

suporte/urls.py
from django.conf.urls import url
from suporte import views

urlpatterns = [
    url(r'licenses/$', views.license_list, name='licenses'),
    url(r'licenses/save/$', views.license_save, name='license_save'),
    url(r'licenses/update/(?P<pk>\d+)/$', views.license_update, name='license_update'),
    url(r'licenses/delete/(?P<pk>\d+)/$', views.license_delete, name='license_delete'),
    url(r'licenses/stop_send_warning/$', views.licese_stop_send_warning, name='stop_send_warning'),
]

websistesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # core urls
    url(r'^contato/$', core_views.contact, name='contato'),

    url(r'^core/cliente/autocomplete/$', core_views.autocomplete_clientes),
    url(r'^core/produto/autocomplete/$', core_views.autocomplete_produtos),

    url(r'^techcd/', include('core.urls', namespace='techcd')),
    url(r'^suporte/', include('suporte.urls', namespace='suporte')),
    url(r'^boletos/', include('faturamento.urls', namespace='boletos')),
    url(r'^contato/enviado/$', TemplateView.as_view(template_name='snippet/obrigado-pelo-contato.html'),
        name='obrigado_pelo_contato'),

    # index login
    url(r'^index/$', TemplateView.as_view(template_name='index.html'), name='home'),

    # index public
    url(r'^$', TemplateView.as_view(template_name='public.html'), name='public'),

    # auth urls
    url(r'^login/$', auth_views.login, {'template_name': u'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

]

suporte/models.py
from django.db import models

# Create your models here.

class PerennityLicense(models.Model):
    TRIAL = 0
    DEMO = 1
    FULL = 2
    STATUS_LICENSE = (
        (TRIAL, 'Amostra'),
        (DEMO, 'Demonstração'),
        (FULL, 'Licenciado'),
    )

    tecnico = models.ForeignKey('auth.User', related_name='tecnicos')
    cliente = models.CharField('Cliente', max_length=250)
    mac_address = models.CharField('MacAddress', max_length=250)
    serial = models.CharField('SN', max_length=100, unique=True, null=True, blank=True)
    installed = models.DateField('Instalado', null=True, blank=True)
    valid = models.DateField('Valido', null=True, blank=True)
    key = models.TextField('Chave', null=True, blank=True)
    active = models.NullBooleanField('Licença Ativa', default=True)
    tipo_license = models.PositiveIntegerField('Status', choices=STATUS_LICENSE, default=TRIAL)

    nao_enviar_aviso =  models.NullBooleanField(default=False)
    data_ultimo_aviso =  models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-valid']

    def __str__(self):
        return '%s | %s' % (self.cliente, self.mac_address)

    @property
    def tecnico_name(self):
        names = (self.tecnico.first_name, self.tecnico.last_name)
        return ' '.join(names) or None

suporte/forms.py
from django import forms

from core.models import Produtos
from suporte.models import PerennityLicense
from django.contrib.auth.models import User



class LicenseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(LicenseForm, self).__init__(*args, **kwargs)
        self.fields['tecnico'].queryset = User.objects.filter(groups__name='SUPORTE')

    class Meta:
        model = PerennityLicense
        fields = ('cliente','active' ,'mac_address','tecnico',
                 'tipo_license', 'serial', 'valid', 'installed', 'key',)

suporte/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.template.loader import render_to_string

from suporte.forms import LicenseForm
from suporte.models import PerennityLicense


# def não sendo mais usanda mais vou deixar ai por enquato...  para alguma consulta sei la
def serialze(license):
    keys = ('id', 'cliente', 'mac_address', 'serial', 'valid', 'installed', 'key', 'tecnico_name')
    return {key: getattr(license, key) for key in keys}

@login_required
def license_list(request):
    '''List the objects in table table_license '''

    search = request.GET.get('lisence-search')

    if search == None or search == '':
        licenses_list = PerennityLicense.objects.all().order_by('-id')

    else:
        licenses_list = PerennityLicense.objects.filter(Q(cliente__contains=search) |
                                                        Q(mac_address__contains=search) |
                                                        Q(serial__contains=search)).order_by('-id')

    paginator = Paginator(licenses_list, 5)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        licenses = paginator.page(page)

    except(EmptyPage, InvalidPage):
        licenses = paginator.page(paginator.num_pages)

    add_form = LicenseForm()
    context = {
        'add_form': add_form,
        'licenses': licenses,
    }
    return render(request, 'license_perennity.html', context)

@login_required
def license_form_service(request, form, template, sucess_message):
    data = {}

    if request.method == 'POST':
        if form.is_valid():
            license = form.save(commit=False)
            license.tecnico = request.user
            license.save()

            licenses_list = PerennityLicense.objects.all()
            paginator = Paginator(licenses_list, 5)
            try:
                page = int(request.GET.get('page','1'))
            except:
                page = 1
            try:
                licenses = paginator.page(page)
            except(EmptyPage, InvalidPage):
                licenses = paginator.page(paginator.num_pages)

            data['table_license'] = render_to_string('snippet/license_table.html',
                                                     {'licenses': licenses}, request=request)
            data['is_form_valid'] = True
            data['js_title_message'] = sucess_message
            data['js_cliente'] = license.cliente
            data['js_serial'] = license.serial
        else:
            data['is_form_valid'] = False
            data['js-message'] = 'um erro ocorreu com este formulario'

    data['form_html'] = render_to_string(template, {'form': form}, request=request)
    return JsonResponse(data)

def licese_stop_send_warning(request):
    data = {}

    if request.method == 'POST':
        license = PerennityLicense.objects.filter(Q(cliente=request.POST.get('cliente')) &
                                                  Q(serial=request.POST.get('serial')) &
                                                  Q(mac_address=request.POST.get('mac_address'))
                                                  ).first()
        license.nao_enviar_aviso = True
        license.data_ultimo_aviso = datetime.now()
        license.save()

        data['js_title_message'] = 'Emails de Aviso ão serão mais enviado! '
        data['js_cliente'] = license.cliente
        data['js_serial'] = license.serial

    return JsonResponse(data)

def license_save(request):
    if request.method == 'POST':
        form = LicenseForm(request.POST)
    else:
        form = LicenseForm()
    return license_form_service(request, form, 'snippet/license_form_create.html', 'Licença criada com sucesso !')

def license_update(request, pk):
    license = get_object_or_404(PerennityLicense, pk=pk)

    if request.method == 'POST':
        form = LicenseForm(request.POST, instance=license)
    else:
        form = LicenseForm(instance=license)
    return license_form_service(request, form, 'snippet/license_form_update.html', 'Licença alterada  com sucesso !')

def license_delete(request, pk):
    data = {}
    license = get_object_or_404(PerennityLicense, pk=pk)

    if request.method == 'POST':
        license.delete()
        licenses = PerennityLicense.objects.all()
        data['table_license'] = render_to_string('snippet/license_table.html', {'licenses': licenses}, request=request)

        data['is_form_valid'] = True
        data['js_title_message'] = 'Licença Deletada com sucesso!'
        data['js_cliente'] = license.cliente
        data['js_serial'] = license.serial

    else:
        data['is_form_valid'] = False
        data['form_html'] = render_to_string('snippet/license_form_delete.html',
                                             {'form': LicenseForm(instance=license)}, request=request)

    return JsonResponse(data)

suporte/templates/snippet/alert_modal.html
<!-- Modal -->
  <div class="modal fade" id="alert" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" id="js-alert-title"></h4>
        </div>
        <div class="modal-body">
          <p id="js-alert-serial"></p>
          <p id="js-alert-cliente"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

suporte/templates/snippet/license_form.html
{% load widget_tweaks %}

<div class="row">
    <div class="col-md-3 form-group {% if form.active.errors %} has-error {% endif %}">
        <label for="{{ form.active.id_for_label }}">{{ form.active.label }}</label>
        {% render_field form.active class="form-control checkbox-inline"%}
        {% for error in form.active.erros %}
        <p class="help-block"> {{ error }}</p>
        {% endfor %}
    </div>
</div>


<div class="form-group{% if form.cliente.errors %} has-error {% endif %}">
    <label for="{{ form.cliente.id_for_label }}">{{ form.cliente.label }}</label>
    {% render_field form.cliente class="form-control autocomplete" %}
    {% for error in form.cliente.errors %}
    <p class="help-block">{{ error }}</p>
    {% endfor %}
</div>


<div class="row">
    <div class="col-md-6 form-group{% if form.tipo_license.errors %} has-error {% endif %}">
        <label for="{{ form.tipo_license.id_for_label }}">{{ form.tipo_license.label }}</label>
        {% render_field form.tipo_license class="form-control" %}
        {% for error in form.tipo_license.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>

    <div class="col-md-6 form-group{% if form.tecnico.errors %} has-error {% endif %}">
        <label for="{{ form.tecnico.id_for_label }}">{{ form.tecnico.label }}</label>
        {% render_field form.tecnico class="form-control" %}
        {% for error in form.tecnico.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>

</div>

<div class="row">
    <div class="col-md-6 form-group{% if form.serial.errors %} has-error {% endif %}">
        <label for="{{ form.serial.id_for_label }}">{{ form.serial.label }}</label>
        {% render_field form.serial class="form-control" %}
        {% for error in form.serial.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>


    <div class="col-md-6 form-group{% if form.mac_address.errors %} has-error {% endif %}">
        <label for="{{ form.mac_adress.id_for_label }}">{{ form.mac_address.label }}</label>
        {% render_field form.mac_address class="form-control" %}
        {% for error in form.mac_address.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
</div>
<div class="row">
    <div class="col-md-6 form-group{% if form.installed.errors %} has-error {% endif %}">
        <label for="{{ form.installed.id_for_label }}">{{ form.installed.label }}</label>
        {% render_field form.installed class="form-control calender" %}
        {% for error in form.installed.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
    <div class="col-md-6 form-group{% if form.valid.errors %} has-error {% endif %}">
        <label for="{{ form.valid.id_for_label }}">{{ form.valid.label }}</label>
        {% render_field form.valid class="form-control calender" %}
        {% for error in form.valid.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
</div>
<div class="form-group{% if form.key.errors %} has-error {% endif %}">
    <label for="{{ form.key.id_for_label }}">{{ form.key.label }}</label>
    {% render_field form.key class="form-control" rows="4" %}
    {% for error in form.key.errors %}
    <p class="help-block">{{ error }}</p>
    {% endfor %}
</div>

suporte/templates/snippet/license_form_create.html
<form action="{% url 'suporte:license_save' %}" method="post" class="js-form-license-save" >
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>

        <h4 class="modal-title ">:: {% block title_modal %} ADD  LICENÇA {% endblock %}:: </h4>

        <span id="client_label_id"> </span>
        <span id="client_id"></span>
        <span class="pull-right" id="id_tecnico"></span>
    </div>

    <div class="modal-body">

        {% include 'snippet/license_form.html' %}

    </div> <!-- end modal-body -->

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary js-license-save">Salvar !</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</form>

suporte/templates/snippet/license_form_delete.html
{% load utils_extras %}
<form action="{% url 'suporte:license_delete' form.instance.pk %}" method="POST" class="js-form-license-delete" >
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>

        <h4 class="modal-title ">:: {% block title_modal %} DELETAR  LICENÇA {% endblock %}:: </h4>

        <span id="client_label_id"> </span>
        <span id="client_id"></span>
        <span class="pull-right" id="id_tecnico"></span>
    </div>

    <div class="modal-body">

        {% include 'snippet/license_form.html' %}


    </div> <!-- end modal-body -->

    <div class="modal-footer">
        {% if request.user|has_group:"SUPORTE ADMIN" %}
        <button type="submit" class="btn btn-danger js-form-license-delete">Deletar!</button>
        {% endif %}
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</form>

suporte/templates/snippet/license_form_update.html
{% load utils_extras %}
<form action="{% url 'suporte:license_update' form.instance.pk  %}" method="post" class="js-form-license-update" >
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>

        <h4 class="modal-title ">:: {% block title_modal %} UPDATE  LICENÇA {% endblock %}:: </h4>

        <span id="client_label_id"> </span>
        <span id="client_id"></span>
        <span class="pull-right" id="id_tecnico"></span>
    </div>

    <div class="modal-body">

        {% include 'snippet/license_form.html' %}

    </div> <!-- end modal-body -->

    <div class="modal-footer">

        {% if request.user|has_group:"SUPORTE ADMIN" %}
        <button type="submit" class="btn btn-default js-send-warning" data-url="{% url 'suporte:stop_send_warning' %}">
            Parar de enviar avisos!
        </button>
        {% endif %}

        {% if request.user|has_group:"SUPORTE" %}
        <button type="submit" class="btn btn-warning js-form-license-update">Alterar!</button>
        {% endif %}

        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</form>

suporte/templates/snippet/license_table.html
{%load utils_extras %}
{% for license in  licenses %}

<tr class="

{% if license.valid|valid_danger %} bg-danger {% endif %}
{% if license.valid|valid_warning %} bg-warning {% endif %}
{% if license.valid|valid_success %} bg-success {% endif %}

" >
        <td data-column="#">{{ license.id}}</td>
        <td data-column="cliente *">{{ license.cliente|upper}}</td>
        <td data-column="mac address *">{{ license.mac_address|upper}}</td>
        <td data-column="serial ">{{ license.serial|upper}}</td>
        <td data-column="validade *">{{ license.valid|date:"d/m/Y"}}</td>

        <td ><button class="btn btn-warning js-license-update" type="button" data-url="{% url 'suporte:license_update' license.id %}">
                <span class="glyphicon glyphicon-pencil"> </span>
        </button></td>

        <td ><button class="btn btn-danger js-license-delete" type="button" data-url="{% url 'suporte:license_delete' license.id %}">
                <span class="glyphicon glyphicon-trash"> </span>
        </button></td>
    </tr>

{% endfor %}