core/urls.py
from django.conf.urls import url
from core import views

urlpatterns = [
    url(r'produtos/$', views.produtos, name='product_list'),
    url(r'produtos/save/$', views.produto_save, name='save_produto'),
    url(r'produtos/update/(?P<pk>\d+)/$', views.produto_update, name='update_produto'),
    url(r'produtos/delete/(?P<pk>\d+)/$', views.produto_delete, name='delete_produto'),

    url(r'clientes/$',views.contrato_client_list, name='contato_cliente_list'),
]

faturamento/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'list/$', views.boleto_list, name='boletos_list'),
    url(r'detail/techcd/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_tech_detail, name='boleto_tech_detail'),
    url(r'detail/data-store/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_data_detail, name='boleto_data_detail'),
    url(r'detail/midia-center/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_midia_detail, name='boleto_midia_detail'),

    url(r'update/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_update, name='boleto_update'),
]

suporte/urls.py
from django.conf.urls import url
from suporte import views

urlpatterns = [
    url(r'licenses/$', views.license_list, name='licenses'),
    url(r'licenses/save/$', views.license_save, name='license_save'),
    url(r'licenses/update/(?P<pk>\d+)/$', views.license_update, name='license_update'),
    url(r'licenses/delete/(?P<pk>\d+)/$', views.license_delete, name='license_delete'),
    url(r'licenses/stop_send_warning/$', views.licese_stop_send_warning, name='stop_send_warning'),
]

websistesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # core urls
    url(r'^contato/$', core_views.contact, name='contato'),

    url(r'^core/cliente/autocomplete/$', core_views.autocomplete_clientes),
    url(r'^core/produto/autocomplete/$', core_views.autocomplete_produtos),

    url(r'^techcd/', include('core.urls', namespace='techcd')),
    url(r'^suporte/', include('suporte.urls', namespace='suporte')),
    url(r'^boletos/', include('faturamento.urls', namespace='boletos')),
    url(r'^contato/enviado/$', TemplateView.as_view(template_name='snippet/obrigado-pelo-contato.html'),
        name='obrigado_pelo_contato'),

    # index login
    url(r'^index/$', TemplateView.as_view(template_name='index.html'), name='home'),

    # index public
    url(r'^$', TemplateView.as_view(template_name='public.html'), name='public'),

    # auth urls
    url(r'^login/$', auth_views.login, {'template_name': u'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

]

core/models/models_pytech.py
from django.contrib.auth.models import User
from django.db import models



class ProdutoPytech(models.Model):
    cliente = models.ForeignKey('ClientePytech', null=True, blank=True, related_name='produtos')
    desc = models.CharField('DESC', max_length=100)
    ativo = models.NullBooleanField(default=True)
    sn = models.CharField('SN', max_length=18)

    def __str__(self):
        return '{} | {}'.format(self.desc, self.sn)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Pytech Produto '
        verbose_name_plural = 'Pytech Produtos'


class GrupoClientePytech(models.Model):
    name = models.CharField('Nome do Grupo', max_length=100)


class ClientePytech(models.Model):
    HOSPITAL = 1
    CLINICA = 2
    GRAFICA = 3
    IGREJA = 4
    INDUSTRIA = 5
    SEGURANÇA = 6
    OUTROS = 7

    TIPO_CLIENTE = (
        (HOSPITAL, 'Hospital'),
        (CLINICA, 'Clinica Medica'),
        (GRAFICA, 'Graficas'),
        (IGREJA, 'Igrejas'),
        (INDUSTRIA, 'Industrias'),
        (SEGURANÇA, 'Epresas de Seguranças'),
        (OUTROS, 'Outros'),
    )

    id_reff = models.PositiveIntegerField('ID Sistech')
    name = models.CharField('Razão Social', max_length=255)
    nick_name = models.CharField('Apelido', max_length=200, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    active = models.NullBooleanField(default=False)
    tipo = models.PositiveIntegerField('Ramo', default=HOSPITAL, choices=TIPO_CLIENTE)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['-created']

    def __str__(self):
        return '{} ({})'.format(self.name, self.nick_name)



class Contact(models.Model):
    SUGESTAO = 1
    SOLITACAO = 2
    RECALAMCAO = 3
    RECALAMCAO_ANONIMA = 4

    TIPO_CATEGORIAS = (
        (SUGESTAO, 'SUGESTÃO'),
        (SOLITACAO, 'SOLITAÇÃO'),
        (RECALAMCAO, 'RECLAMAÇÃO'),
        (RECALAMCAO_ANONIMA, 'RECLAMAÇÃO ANONIMA'),
    )

    nome = models.CharField(max_length=50, null=True, blank=True)
    categoria = models.IntegerField(choices=TIPO_CATEGORIAS, default=SUGESTAO)
    assunto = models.CharField(max_length=100, )
    menssagem = models.TextField()
    data_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, default=0, null=True, blank=True)

    class Meta:
        ordering = ['-data_created']
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.assunto

suporte/models.py
from django.db import models

# Create your models here.

class PerennityLicense(models.Model):
    TRIAL = 0
    DEMO = 1
    FULL = 2
    STATUS_LICENSE = (
        (TRIAL, 'Amostra'),
        (DEMO, 'Demonstração'),
        (FULL, 'Licenciado'),
    )

    tecnico = models.ForeignKey('auth.User', related_name='tecnicos')
    cliente = models.CharField('Cliente', max_length=250)
    mac_address = models.CharField('MacAddress', max_length=250)
    serial = models.CharField('SN', max_length=100, unique=True, null=True, blank=True)
    installed = models.DateField('Instalado', null=True, blank=True)
    valid = models.DateField('Valido', null=True, blank=True)
    key = models.TextField('Chave', null=True, blank=True)
    active = models.NullBooleanField('Licença Ativa', default=True)
    tipo_license = models.PositiveIntegerField('Status', choices=STATUS_LICENSE, default=TRIAL)

    nao_enviar_aviso =  models.NullBooleanField(default=False)
    data_ultimo_aviso =  models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-valid']

    def __str__(self):
        return '%s | %s' % (self.cliente, self.mac_address)

    @property
    def tecnico_name(self):
        names = (self.tecnico.first_name, self.tecnico.last_name)
        return ' '.join(names) or None

core/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url, get_object_or_404
from django.template.loader import render_to_string
from django.db.models import Q
from core.form import ContactForm, ProdutoForm
from core.models import Clientes, Produtos, ProdutoPytech, ContratoCliente, Contrato, TipoContrato, UnidadeNegocio

# Create your views here.
from core.utils import pagination


@login_required
def home(request):
    '''Render my home page'''
    return render(request, 'index.html')


def contact(request):
    template = 'contato.html'
    form = ContactForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            contact = form.save(commit=False)
            if request.user.is_authenticated:
                contact.user = request.user
            contact.save()
            body = render_to_string('snippet/contato.txt', {'contato': contact})
            send_mail(contact.assunto, body,
                      'thiago@techcd.com.br', ['thiago@techcd.com.br'])

            return HttpResponseRedirect(resolve_url('obrigado_pelo_contato'))

    return render(request, template, {'form': form})


def autocomplete(object_list):
    """ Generic autocomplete """
    results = []
    for object in object_list:
        json_ = {}
        json_['id'] = object.cod_cli
        json_['label'] = object.name.upper()
        json_['value'] = object.name.upper()
        results.append(json_)

    data = json.dumps(results)
    return data


@login_required
def autocomplete_clientes(request):
    """ auto complete para clientes, retorna um json com os clientes que conferem com o parametro passado """
    term = request.GET.get('term')
    if term:
        object_list = Clientes.objects.using('techcd').filter(name__contains=term)[:10]
        data = autocomplete(object_list)
        return HttpResponse(data, 'application/json')
    return render(request, 'license_perennity.html')


@login_required
def autocomplete_produtos(request):
    """auto complete para produtos, retorna um json com os mesmo """
    term = request.GET.get('term')
    if term:
        object_list = Produtos.objects.using('techcd').filter(name__icontains=term)[:10]
        for object in object_list:
            print(object)
        data = autocomplete(object_list)
        return HttpResponse(data, 'application/json')
    return render(request, 'produtos.html')


@login_required
def produtos(request):
    _search = request.GET.get('search')
    print(_search)

    if _search is not None:
        product_list = ProdutoPytech.objects.filter(Q(sn=_search) | Q(desc__contains=_search) & Q(ativo=True))
    else:
        product_list = ProdutoPytech.objects.filter(ativo=True)
    produto_paginator = pagination(request, product_list, 7)
    context = {
        'produto': produto_paginator
    }
    return render(request, 'produtos.html', context)


@login_required
def produto_form_services(request, form, template_name, message):
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            produtos = ProdutoPytech.objects.filter(ativo=True)
            produto_paginator = pagination(request, produtos)
            data['is_form_valid'] = True
            data['message'] = message
            data['html_table'] = render_to_string('produtos/produto_table.html',
                                                  {'produto': produto_paginator}, request=request)
        else:
            data['is_form_valid'] = False
            data['message'] = 'erros foram encontrados durante o processo, verifique tente novamente.'
            data['html_form'] = \
                render_to_string(template_name, context={'form': form}, request=request)

    else:
        data['html_form'] = render_to_string(template_name, context={'form': form}, request=request)

    return JsonResponse(data)


@login_required
def produto_save(request):
    form = ProdutoForm(request.POST or None)
    return produto_form_services(request, form, 'produtos/produto_modal_create.html',
                                 'Produto incluido com sucesso.')


@login_required
def produto_update(request, pk):
    product = get_object_or_404(ProdutoPytech, pk=pk)
    if request.method == 'POST':
        form = ProdutoForm(request.POST, instance=product)
    else:
        form = ProdutoForm(instance=product)

    return produto_form_services(request, form, 'produtos/produto_update_form.html',
                                 'Produto Alterado com sucesso! ')


@login_required
def produto_delete(request, pk):
    data = {}
    template_name = 'produtos/produto_delete_form.html'
    product = get_object_or_404(ProdutoPytech, pk=pk)
    if request.method == 'POST':
        product.ativo = False
        product.save()
        produtos = ProdutoPytech.objects.filter(ativo=True)
        produto_paginator = pagination(request, produtos)

        data['is_form_valid'] = True
        data['message'] = 'Produto: {} \ndesativado com Sucesso.' \
                          'esse produto pode ser acessado somente na area de administração. ' \
            .format(product.desc)

        data['html_table'] = render_to_string('produtos/produto_table.html',
                                              {'produto': produto_paginator}, request=request)
    else:
        form = ProdutoForm(instance=product)
        data['html_form'] = \
            render_to_string(template_name, context={'form': form}, request=request)

    return JsonResponse(data)


@login_required
def contrato_client_list(request):


    search = request.GET.get('search')
    if search is not None:
        contrato_cliente = ContratoCliente.objects.select_related().using('techcd').filter(
            Q(cod_contrato__num_contrato=search) |
            Q(cod_cli__name__contains=search)
        )
    else:
        contrato_cliente = ContratoCliente.objects.select_related().using('techcd').all()

    contrato_cliente_list = pagination(request, contrato_cliente, 10)
    context = {
        'contrato_cliente_list': contrato_cliente_list
    }
    return render(request, 'client_list.html', context)

core/templates/snippet/_menu.html
{% load utils_extras  %}

<!-- Fixed navbar -->
<div class="row">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand "  href="{% url 'public' %}">Web Tech System</a>
            </div>


            <div id="navbar" class="navbar-collapse collapse">


                {% if request.user.is_authenticated  %}
                <ul class="nav navbar-nav">

                    <!-- Faturamento   -->

                    {% if user|has_group:"FATURAMENTO" %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">FATURAMENTO<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'boletos:boletos_list' %}">Boletos</a></li>
                            <!--<li><a href="#">Update Nfe</a></li>-->

                            <!--
                              <li><a href="#">Something else here</a></li>
                              <li role="separator" class="divider"></li>
                              <li class="dropdown-header">Nav header</li>
                              <li><a href="#">Separated link</a></li>
                              <li><a href="#">One more separated link</a></li> -->
                        </ul>

                        {% endif  %}




                        {% if user|has_group:"SISTEMAS" %}
                    </li><!-- Suporte    -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">SUPORTE <span class="caret"></span></a>
                        <ul class="dropdown-menu">

                            <li><a href="{% url 'suporte:licenses' %}">Licensa Perennity </a></li>
                            <!--<li><a href="#">Cliente com Contratos </a></li>-->

                            <!--
                          <li><a href="#">Something else here</a></li>
                          <li role="separator" class="divider"></li>
                          <li class="dropdown-header">Nav header</li>
                          <li><a href="#">Separated link</a></li>
                          <li><a href="#">One more separated link</a></li>
                          -->
                        </ul>
                        {% endif %}

                    </li>



                     {% if user|has_group:"SUPORTE" %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> CADASTRO <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'techcd:contato_cliente_list' %}">Contratos Sistech </a></li>
                            <li><a href="{% url 'techcd:product_list' %}">Produtos </a></li>


                            <!--
                              <li><a href="#">Something else here</a></li>
                              <li role="separator" class="divider"></li>
                              <li class="dropdown-header">Nav header</li>
                              <li><a href="#">Separated link</a></li>
                              <li><a href="#">One more separated link</a></li> -->
                        </ul>

                        {% endif  %}



                </ul>
                {% endif %}


                <ul class="nav navbar-nav navbar-right">

                    <li class="{% if request.resolver_match.url_name == 'contato'  %} active {% endif %}">
                        <a href="{% url 'contato' %}">CONTATO</a></li>


                    {% if request.user.is_authenticated  %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <!-- The Profile picture inserted via div class below, with shaping provided by Bootstrap -->
                            <div class="img-rounded profile-img"></div>
                            {{ request.user|upper }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">

                            {% if request.user.is_superuser %}
                            <li>
                                <a href="{% url 'admin:index' %}">Admin</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            {% endif %}
                            <li><a href="{% url 'logout' %}">Sair</a></li>
                        </ul>
                    </li>



                    {% else %}

                    <li class="{% if request.resolver_match.url_name ==  'login' %}active {% endif %}">
                        <a href="{% url 'login' %}">LOGIN</a></li>

                    {% endif %}


                </ul>


            </div><!--/.nav-collapse -->

        </div>
    </nav>
</div>

core/templates/snippet/feedback_contato.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<h1 class="page-header">Contribua com sua opinião </h1>

<div class="row">
        <div class="row">
            <div class="col-md-8">
            <h4> FeedBack </h4>
            </div>
            <div class=>
            <h4> Envie sua Sugestão. </h4>
            </div>
        </div>

      <div class="col-md-8">


        <div class="row" style="">

            <div class="input-group">
                <div class="input-group-btn">
                    <button class="btn btn-info">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>

                <input id="table-input" type="Search" placeholder="Pesquisar ..."
                       class="form-control" onkeypress="searchTable()" />

            </div>


            <table id="table-contact" class="table table-striped table-hover table-sm">
                <thead class="thead-inverse">
                <tr>
                    <th colspan="4"></th>
                </tr>
                <tr class="bg-success">
                    <th>#</th>
                    <th>Assunto</th>
                    <th>Categoria</th>
                    <th>Usuario</th>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Larry</td>
                    <td>the Bird</td>
                    <td>@twitter</td>
                </tr>
                <tr>
                    <th colspan="4" class="bg-warning text-center"> Não foi encontrado nenhum resultado</th>
                </tr>
                </tbody>
                <tfoot>

                </tfoot>
            </table>
        </div>
    </div>


</div>

{% endblock %}

{% block js_extra %}
<!-- JQUERY EXTRAR PARA TABELAS PLUGIN https://datatables.net/-->
<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/apps.js' %}"></script>
<script>
function searchTable() {
  // Declare variables
   var input, filter, table, tr, td, i;
    input = document.getElementById("table-input");
    filter = input.value.toUpperCase();
    table = document.getElementById("table-contact");
    tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

{% endblock %}

core/templates/snippet/license_form_create.html
<form action="{% url 'license_save' %}" method="post" class="js-form-license-save" >
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>

        <h4 class="modal-title ">:: {% block title_modal %} ADD  LICENÇA {% endblock %}:: </h4>

        <span id="client_label_id"> </span>
        <span id="client_id"></span>
        <span class="pull-right" id="id_tecnico"></span>
    </div>

    <div class="modal-body">

        {% include 'snippet/license_form.html' %}

    </div> <!-- end modal-body -->

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary js-license-save">Salvar !</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</form>

core/templates/snippet/license_form_delete.html
{% load utils_extras %}
<form action="{% url 'license_delete' form.instance.pk %}" method="POST" class="js-form-license-delete" >
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>

        <h4 class="modal-title ">:: {% block title_modal %} DELETAR  LICENÇA {% endblock %}:: </h4>

        <span id="client_label_id"> </span>
        <span id="client_id"></span>
        <span class="pull-right" id="id_tecnico"></span>
    </div>

    <div class="modal-body">

        {% include 'snippet/license_form.html' %}


    </div> <!-- end modal-body -->

    <div class="modal-footer">
        {% if request.user|has_group:"SUPORTE ADMIN" %}
        <button type="submit" class="btn btn-danger js-form-license-delete">Deletar!</button>
        {% endif %}
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</form>

core/templates/snippet/license_form_update.html
{% load utils_extras %}
<form action="{% url 'license_update' form.instance.pk  %}" method="post" class="js-form-license-update" >
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>

        <h4 class="modal-title ">:: {% block title_modal %} UPDATE  LICENÇA {% endblock %}:: </h4>

        <span id="client_label_id"> </span>
        <span id="client_id"></span>
        <span class="pull-right" id="id_tecnico"></span>
    </div>

    <div class="modal-body">

        {% include 'snippet/license_form.html' %}

    </div> <!-- end modal-body -->

    <div class="modal-footer">

        {% if request.user|has_group:"SUPORTE ADMIN" %}
        <button type="submit" class="btn btn-default js-send-warning" data-url="{% url 'stop_send_warning' %}">
            Parar de enviar avisos!
        </button>
        {% endif %}

        {% if request.user|has_group:"SUPORTE" %}
        <button type="submit" class="btn btn-warning js-form-license-update">Alterar!</button>
        {% endif %}

        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</form>

core/templates/snippet/license_table.html
{%load utils_extras %}
{% for license in  licenses %}

<tr class="

{% if license.valid|valid_danger %} bg-danger {% endif %}
{% if license.valid|valid_warning %} bg-warning {% endif %}
{% if license.valid|valid_success %} bg-success {% endif %}

" >
        <td data-column="#">{{ license.id}}</td>
        <td data-column="cliente *">{{ license.cliente|upper}}</td>
        <td data-column="mac address *">{{ license.mac_address|upper}}</td>
        <td data-column="serial ">{{ license.serial|upper}}</td>
        <td data-column="validade *">{{ license.valid|date:"d/m/Y"}}</td>

        <td ><button class="btn btn-warning js-license-update" type="button" data-url="{% url 'license_update' license.id %}">
                <span class="glyphicon glyphicon-pencil"> </span>
        </button></td>

        <td ><button class="btn btn-danger js-license-delete" type="button" data-url="{% url 'license_delete' license.id %}">
                <span class="glyphicon glyphicon-trash"> </span>
        </button></td>
    </tr>

{% endfor %}

core/templates/snippet/obrigado-pelo-contato.html
{% extends 'base.html' %}

{% block content %}
<h1 class="page-header"> Obrigado Pelo contato ! </h1>
<h2 class="leader">  logo estaremos verificando seu contato</h2>
{% endblock %}