core/urls.py
from django.conf.urls import url
from core import views

urlpatterns = [
    url(r'produtos/$', views.produtos, name='product_list'),
    url(r'produtos/save/$', views.produto_save, name='save_produto'),
    url(r'produtos/update/(?P<pk>\d+)/$', views.produto_update, name='update_produto'),
    url(r'produtos/delete/(?P<pk>\d+)/$', views.produto_delete, name='delete_produto'),

    url(r'clientes/$',views.contrato_client_list, name='contato_cliente_list'),
]

websistesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # core urls
    url(r'^contato/$', core_views.contact, name='contato'),

    url(r'^core/cliente/autocomplete/$', core_views.autocomplete_clientes),
    url(r'^core/produto/autocomplete/$', core_views.autocomplete_produtos),

    url(r'^techcd/', include('core.urls', namespace='techcd')),
    url(r'^suporte/', include('suporte.urls', namespace='suporte')),
    url(r'^boletos/', include('faturamento.urls', namespace='boletos')),
    url(r'^contato/enviado/$', TemplateView.as_view(template_name='snippet/obrigado-pelo-contato.html'),
        name='obrigado_pelo_contato'),

    # index login
    url(r'^index/$', TemplateView.as_view(template_name='index.html'), name='home'),

    # index public
    url(r'^$', TemplateView.as_view(template_name='public.html'), name='public'),

    # auth urls
    url(r'^login/$', auth_views.login, {'template_name': u'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

]

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings


class TechUser(models.Model):
    cod_grupo = models.OneToOneField('GrupoUsuarios', db_column='COD_GRUPO', blank=True, null=True,
                                     related_name='groups')  # Field name made lowercase.
    username = models.CharField(db_column='NOME_USER', primary_key=True, max_length=30,
                                unique=True)  # Field name made lowercase.
    password = models.CharField(db_column='SENHA_USER', max_length=10, blank=True,
                                null=True)  # Field name made lowercase.
    ip = models.CharField(db_column='IP_HOST', max_length=13, blank=True, null=True)  # Field name made lowercase.
    nickname = models.CharField(db_column='APELIDO_USER', max_length=20, blank=True,
                                null=True)  # Field name made lowercase.
    skype = models.CharField(db_column='APELIDO_SKYPE', max_length=40, blank=True,
                             null=True)  # Field name made lowercase.

    def __str__(self):
        return self.username

    class Meta:
        managed = True if settings.RUNNING_UNIT_TESTS else False
        db_table = 'USUARIOS'


class GrupoUsuarios(models.Model):
    cod_grupo = models.BigIntegerField(primary_key=True)
    desc_grupo = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = True if settings.RUNNING_UNIT_TESTS else False
        db_table = 'GRUPO_USUARIOS'

    def __str__(self):
        return self.desc_grupo.upper()


class Contact(models.Model):
    SUGESTAO = 1
    SOLITACAO = 2
    RECALAMCAO = 3
    RECALAMCAO_ANONIMA = 4

    TIPO_CATEGORIAS = (
        (SUGESTAO, 'SUGESTÃO'),
        (SOLITACAO, 'SOLITAÇÃO'),
        (RECALAMCAO, 'RECLAMAÇÃO'),
        (RECALAMCAO_ANONIMA, 'RECLAMAÇÃO ANONIMA'),
    )

    nome = models.CharField(max_length=50, null=True, blank=True)
    categoria = models.IntegerField(choices=TIPO_CATEGORIAS, default=SUGESTAO)
    assunto = models.CharField(max_length=100, )
    menssagem = models.TextField()
    data_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, default=0, null=True, blank=True)

    class Meta:
        ordering = ['-data_created']
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.assunto


class Clientes(models.Model):
    id = models.BigIntegerField(db_column='COD_CLI', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='NOME_CLI', max_length=80, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True if settings.RUNNING_UNIT_TESTS else False
        db_table = 'CLIENTES'

    def __str__(self):
        name = [n.capitalize() for n in self.name.split()]
        return ' '.join(name)


class Categorias(models.Model):
    cod_cat = models.BigIntegerField(db_column='COD_CAT', primary_key=True)  # Field name made lowercase.
    desc_cat = models.CharField(db_column='DESC_CAT', max_length=40, blank=True,
                                null=True)  # Field name made lowercase.
    cod_supercat = models.BigIntegerField(db_column='COD_SUPERCAT', blank=True, null=True)  # Field name made lowercase.
    mostrar_cat = models.CharField(db_column='MOSTRAR_CAT', max_length=17, blank=True,
                                   null=True)  # Field name made lowercase.
    apelido_cat = models.CharField(db_column='APELIDO_CAT', max_length=50, blank=True,
                                   null=True)  # Field name made lowercase.

    def __str__(self):
        return self.desc_cat.upper()

    class Meta:
        managed = True if settings.RUNNING_UNIT_TESTS else False
        db_table = 'CATEGORIAS'
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'


class Produtos(models.Model):
    '''
     categorias relacionada ao suporte 
     174 =  Gravadore 
     42 =  equipamentos 
     45 =  suprimetos epson 
     46 =  serviços 
     49 =  suprimetos rimagem 
     52 =  produtos rimage 
     62 = produtos epson 
     63 = vidar equipametos 
     64 = vidar peças 
     57 = licença
     69 =  monitores 
     71 =  prdutos stratasys 
    '''
    list_cod_cat = [174, 42, 45, 46, 49, 52, 62, 63, 64, 68, 69, 71]

    id = models.BigIntegerField(db_column='COD_PROD', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='DESC_PROD', max_length=300, blank=True,
                            null=True)  # Field name made lowercase.
    min_prod = models.IntegerField(db_column='MIN_PROD', blank=True, null=True)  # Field name made lowercase.
    saldo_prod = models.BigIntegerField(db_column='SALDO_PROD', blank=True, null=True)  # Field name made lowercase.
    teorico_prod = models.BigIntegerField(db_column='TEORICO_PROD', blank=True, null=True)  # Field name made lowercase.
    custoref_prod = models.DecimalField(db_column='CUSTOREF_PROD', max_digits=19, decimal_places=4, blank=True,
                                        null=True)  # Field name made lowercase.
    custo_prod = models.DecimalField(db_column='CUSTO_PROD', max_digits=19, decimal_places=4, blank=True,
                                     null=True)  # Field name made lowercase.

    categoria = models.ForeignKey(Categorias, db_column='COD_CAT', blank=True, null=True,
                                  related_name='categorias')  # Field name made lowercase.

    def __str__(self):
        return self.name.upper()

    class Meta:
        managed = True if settings.RUNNING_UNIT_TESTS else False
        db_table = 'PRODUTOS'
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'


# cadastros para pytech


class ProdutoPytech(models.Model):
    cliente =  models.ForeignKey('ClientePytech', null=True, blank=True, related_name='produtos')
    desc = models.CharField('DESC', max_length=100)
    ativo = models.NullBooleanField(default=True)
    sn = models.CharField('SN', max_length=18)

    def __str__(self):
        return '{} | {}'.format(self.desc, self.sn)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Pytech Produto '
        verbose_name_plural = 'Pytech Produtos'


class GrupoClientePytech(models.Model):
    name = models.CharField('Nome do Grupo', max_length=100)


class ClientePytech(models.Model):
    HOSPITAL = 1
    CLINICA = 2
    GRAFICA = 3
    IGREJA = 4
    INDUSTRIA = 5
    SEGURANÇA = 6
    OUTROS = 7

    TIPO_CLIENTE = (
        (HOSPITAL, 'Hospital'),
        (CLINICA, 'Clinica Medica'),
        (GRAFICA, 'Graficas'),
        (IGREJA, 'Igrejas'),
        (INDUSTRIA, 'Industrias'),
        (SEGURANÇA, 'Epresas de Seguranças'),
        (OUTROS, 'Outros'),
    )

    id_reff = models.PositiveIntegerField('ID Sistech')
    name = models.CharField('Razão Social', max_length=255)
    nick_name = models.CharField('Apelido', max_length=200, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    active = models.NullBooleanField(default=False)
    tipo = models.PositiveIntegerField('Ramo', default=HOSPITAL, choices=TIPO_CLIENTE)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['-created']

    def __str__(self):
        return '{} ({})'.format(self.name, self.nick_name)

core/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url, get_object_or_404
from django.template.loader import render_to_string
from django.db.models import Q
from core.form import ContactForm, ProdutoForm
from core.models import Clientes, Produtos, ProdutoPytech, ContratoCliente, Contrato, TipoContrato, UnidadeNegocio

# Create your views here.
from core.utils import pagination


@login_required
def home(request):
    '''Render my home page'''
    return render(request, 'index.html')


def contact(request):
    template = 'contato.html'
    form = ContactForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            contact = form.save(commit=False)
            if request.user.is_authenticated:
                contact.user = request.user
            contact.save()
            body = render_to_string('snippet/contato.txt', {'contato': contact})
            send_mail(contact.assunto, body,
                      'thiago@techcd.com.br', ['thiago@techcd.com.br'])

            return HttpResponseRedirect(resolve_url('obrigado_pelo_contato'))

    return render(request, template, {'form': form})


def autocomplete(object_list):
    """ Generic autocomplete """
    results = []
    for object in object_list:
        json_ = {}
        json_['id'] = object.cod_cli
        json_['label'] = object.name.upper()
        json_['value'] = object.name.upper()
        results.append(json_)

    data = json.dumps(results)
    return data


@login_required
def autocomplete_clientes(request):
    """ auto complete para clientes, retorna um json com os clientes que conferem com o parametro passado """
    term = request.GET.get('term')
    if term:
        object_list = Clientes.objects.using('techcd').filter(name__contains=term)[:10]
        data = autocomplete(object_list)
        return HttpResponse(data, 'application/json')
    return render(request, 'license_perennity.html')


@login_required
def autocomplete_produtos(request):
    """auto complete para produtos, retorna um json com os mesmo """
    term = request.GET.get('term')
    if term:
        object_list = Produtos.objects.using('techcd').filter(name__icontains=term)[:10]
        for object in object_list:
            print(object)
        data = autocomplete(object_list)
        return HttpResponse(data, 'application/json')
    return render(request, 'produtos.html')


@login_required
def produtos(request):
    _search = request.GET.get('search')
    print(_search)

    if _search is not None:
        product_list = ProdutoPytech.objects.filter(Q(sn=_search) | Q(desc__contains=_search) & Q(ativo=True))
    else:
        product_list = ProdutoPytech.objects.filter(ativo=True)
    produto_paginator = pagination(request, product_list, 7)
    context = {
        'produto': produto_paginator
    }
    return render(request, 'produtos.html', context)


@login_required
def produto_form_services(request, form, template_name, message):
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            produtos = ProdutoPytech.objects.filter(ativo=True)
            produto_paginator = pagination(request, produtos)
            data['is_form_valid'] = True
            data['message'] = message
            data['html_table'] = render_to_string('produtos/produto_table.html',
                                                  {'produto': produto_paginator}, request=request)
        else:
            data['is_form_valid'] = False
            data['message'] = 'erros foram encontrados durante o processo, verifique tente novamente.'
            data['html_form'] = \
                render_to_string(template_name, context={'form': form}, request=request)

    else:
        data['html_form'] = render_to_string(template_name, context={'form': form}, request=request)

    return JsonResponse(data)


@login_required
def produto_save(request):
    form = ProdutoForm(request.POST or None)
    return produto_form_services(request, form, 'produtos/produto_modal_create.html',
                                 'Produto incluido com sucesso.')


@login_required
def produto_update(request, pk):
    product = get_object_or_404(ProdutoPytech, pk=pk)
    if request.method == 'POST':
        form = ProdutoForm(request.POST, instance=product)
    else:
        form = ProdutoForm(instance=product)

    return produto_form_services(request, form, 'produtos/produto_update_form.html',
                                 'Produto Alterado com sucesso! ')


@login_required
def produto_delete(request, pk):
    data = {}
    template_name = 'produtos/produto_delete_form.html'
    product = get_object_or_404(ProdutoPytech, pk=pk)
    if request.method == 'POST':
        product.ativo = False
        product.save()
        produtos = ProdutoPytech.objects.filter(ativo=True)
        produto_paginator = pagination(request, produtos)

        data['is_form_valid'] = True
        data['message'] = 'Produto: {} \ndesativado com Sucesso.' \
                          'esse produto pode ser acessado somente na area de administração. ' \
            .format(product.desc)

        data['html_table'] = render_to_string('produtos/produto_table.html',
                                              {'produto': produto_paginator}, request=request)
    else:
        form = ProdutoForm(instance=product)
        data['html_form'] = \
            render_to_string(template_name, context={'form': form}, request=request)

    return JsonResponse(data)


@login_required
def contrato_client_list(request):


    search = request.GET.get('search')
    if search is not None:
        contrato_cliente = ContratoCliente.objects.select_related().using('techcd').filter(
            Q(cod_contrato__num_contrato=search) |
            Q(cod_cli__name__contains=search)
        )
    else:
        contrato_cliente = ContratoCliente.objects.select_related().using('techcd').all()

    contrato_cliente_list = pagination(request, contrato_cliente, 10)
    context = {
        'contrato_cliente_list': contrato_cliente_list
    }
    return render(request, 'client_list.html', context)

core/templates/_menu.html
{% load utils_extras  %}

 <!-- Fixed navbar -->
 <div class="row">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Web Tech Sistem</a>
        </div>





        <div id="navbar" class="navbar-collapse collapse">


            {% if request.user.is_authenticated  %}
          <ul class="nav navbar-nav">

            <!-- Faturamento   -->

              {% if user|has_group:"FATURAMENTO" %}
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                 aria-expanded="false">FATURAMENTO<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Boletos</a></li>
                <li><a href="#">Update Nfe</a></li>

                  <!--
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li> -->
              </ul>

               {% endif  %}

               {% if user|has_group:"SISTEMAS" %}
              </li><!-- Suporte    -->
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                 aria-expanded="false">SUPORTE <span class="caret"></span></a>
              <ul class="dropdown-menu">

                  <li><a href="{% url 'licenses' %}">Licensa Perennity </a></li>

                  <!--
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
                -->
              </ul>
                {% endif %}

              </li>



          </ul>
            {% endif %}


            <ul class="nav navbar-nav navbar-right">



                    {% if request.user.is_authenticated  %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <!-- The Profile picture inserted via div class below, with shaping provided by Bootstrap -->
                        <div class="img-rounded profile-img"></div>
                        {{ request.user.username }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Settings</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#">Log out</a>
                        </li>
                    </ul>
                </li>



                <li><a href="{% url 'logout' %}">Sair</a></li>
                    {% else %}

                  <li CLASS="active"><a href="{% url 'login' %}">LOGIN</a></li>

                    {% endif %}


            </ul>


        </div><!--/.nav-collapse -->

      </div>
    </nav>
 </div>

core/templates/base.html
{% load static %}
{% load utils_extras  %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} WebSisTeCH {% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/me.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css" rel="stylesheet"/>

    <!-- bootstrap calendar -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script type="text/javascript" src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->



<style>
.ui-autocomplete{
	z-index:1050;
}
</style>

</head>
<body>


{% include 'snippet/_menu.html' %}

<div class="container" style="margin-top:50px; ">
    {% block content %}



    {% endblock %}
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js'%}"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>

<!-- bootstrap validation -->
<script  type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>

<!--&lt;!&ndash; jquery  data table &ndash;&gt;-->
<script  src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script  src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
<script  src="{% static 'js/jquery.bsFormAlerts.js' %}"></script>



<!-- bootstrap calendar -->
<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/locales/bootstrap-datepicker.pt-BR.js' %}"></script>


{% block js_extra%}

{% endblock %}


</body>
</html>

core/templates/client_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <h1 class="page-header">Clientes</h1>

    <div class="row">
        <div class="col-md-8">
            <form action="{% url 'techcd:contato_cliente_list' %}" method="GET">
                {% csrf_token %}
                <div class="input-group">

                    <input id="search" name="search" class="form-control" type="text"
                           placeholder="Buscar por: Numero de Contrato ou Nome de Cliente"
                           autofocus>

                    <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
                </div> <!--  div input group -->
            </form>
        </div><!-- col 8 row  -->
    </div><!--  row div search-bar -->

    <div style="height:2em;"></div>
    <div class="row">

        <table id="table-client"class="table table-condensed table-hover">
            <thead class="thead-inverse">
            <tr>
                <th colspan="7"></th>
            </tr>

            <tr class="bg-success">
                <th>#</th>
                <th>CLIENTE</th>
                <th>CONTRATO</th>
                <th>U. NEGOCIO</th>
                <th>T. CONTRATO</th>
                <th>EMPRESA</th>
                <th>STATUS</th>
            </tr>

            </thead>

            <tbody>
            <tr>
                {% include 'clientes/cliente_table.html' %}
            </tr>
            </tbody>

        </table>
            {% include 'pagination.html' with object=contrato_cliente_list %}

    </div>




</div>


{% endblock %}

core/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h4 class="page-header">Bem vindo, {{ request.user }}</h4>
</div>

{% endblock  %}

core/templates/pagination.html
<div class="row text-center">
    <div class="pagination">
        {{ object.render }}
    </div>
</div>

core/templates/produtos.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<h1 class="page-header"> Produtos </h1>




<div class="row">

    <div class="row">

        <div class="form-group">
            <button id="add-produto" type="button" class="btn btn-primary js-modal-prodtudos"
                    data-url="{% url 'techcd:save_produto' %}">
                <span class="glyphicon glyphicon-plus"></span>
                Produtos
            </button>
        </div>

        <form action="" method="GET" >
            {% csrf_token %}



            <div class="col-md-6" style="margin-bottom:2em">
                <div class="row">
                    <form action="{% url 'techcd:product_list' %}" method="get" class="">
                        <div class="input-group">
                            <input name="search" type="text" class="form-control"
                                   placeholder="Pesquisar por: Descrição de Produto ou Serial "
                                   autofocus />

                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                            </button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>

        </form>
    </div>
</div>


<div class="row" style="">

    <table id="produto-table" class="table table-condensed table-hover">
        <thead class="thead-inverse">
        <tr>
            <th colspan="4"></th>
        </tr>
        <tr class="bg-success">
            <th>#</th>
            <th>DESCRIÇÃO</th>
            <th>SERIAL NUMBER </th>
            <th>EDIT</th>
            <th>DESATIVAR</th>
        </tr>
        </thead>

        <tbody>

        {% include 'produtos/produto_table.html' %}

        </tbody>
    </table>

    {% include 'pagination.html' with object=produto %}

</div>

<!-- Modal -->
<div class="modal fade" id="modal-produtos" tabindex="-1" role="dialog"
     aria-labelledby="modal-produtos" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">


        </div>
    </div>
</div>

{% endblock %}

{% block js_extra %}
<!-- JQUERY EXTRAR PARA TABELAS PLUGIN https://datatables.net/-->
<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/locales/bootstrap-datepicker.pt-BR.js' %}"></script>
<script  src="{% static 'js/jquery.bsFormAlerts.js' %}"></script>
<script type="text/javascript" src="{% static 'js/apps.js' %}"></script>
<script>

function searchTable() {
  // Declare variables
   var input, filter, table, tr, td, i;
    input = document.getElementById("table-input");
    filter = input.value.toUpperCase();
    table = document.getElementById("table-contact");
    tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

{% endblock %}

core/templates/public.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

  <h1 class="page-header">TechCD  - INTRANET -</h1>

    <div class="jumbotron">

        <p class="lead">Essa essa uma pagina em desenvolvimento da techcd para auxilio  de alguns processo internos para ter acesso é só logar

            com seu usuário e senha do sistech, em caso de erro, envie um email para o <strong>thiago@techcd.com.br</strong>

            ou envie uma mensagem pelo WhatsApp  para <strong>0117051-3508 </strong>, você pode falar comigo também através  do

            <strong>skype:oliveiravicente.net</strong></p> <br />

        <h5>Envie nos a sua sugestão !</h5>

            <h4>Obrigado !!!</h4>

            <br />

        <a role="button"  href="{% url 'contato' %}" class="btn btn-lg btn-success"> Contato </a>
    </div>


</div>

{% endblock  %}