core/urls.py
from django.conf.urls import url
from core import views

urlpatterns = [
    url(r'produtos/$', views.produtos, name='product_list'),
    url(r'produtos/save/$', views.produto_save, name='save_produto'),
    url(r'produtos/update/(?P<pk>\d+)/$', views.produto_update, name='update_produto'),
    url(r'produtos/delete/(?P<pk>\d+)/$', views.produto_delete, name='delete_produto'),

    url(r'clientes/$',views.contrato_client_list, name='contato_cliente_list'),
]

faturamento/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'list/$', views.boleto_list, name='boletos_list'),
    url(r'detail/techcd/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_tech_detail, name='boleto_tech_detail'),
    url(r'detail/data-store/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_data_detail, name='boleto_data_detail'),
    url(r'detail/midia-center/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_midia_detail, name='boleto_midia_detail'),

    url(r'update/boleto/(?P<nnum_bol>[\d]+)/$', views.boleto_update, name='boleto_update'),
]

websistesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # core urls
    url(r'^contato/$', core_views.contact, name='contato'),

    url(r'^core/cliente/autocomplete/$', core_views.autocomplete_clientes),
    url(r'^core/produto/autocomplete/$', core_views.autocomplete_produtos),

    url(r'^techcd/', include('core.urls', namespace='techcd')),
    url(r'^suporte/', include('suporte.urls', namespace='suporte')),
    url(r'^boletos/', include('faturamento.urls', namespace='boletos')),
    url(r'^contato/enviado/$', TemplateView.as_view(template_name='snippet/obrigado-pelo-contato.html'),
        name='obrigado_pelo_contato'),

    # index login
    url(r'^index/$', TemplateView.as_view(template_name='index.html'), name='home'),

    # index public
    url(r'^$', TemplateView.as_view(template_name='public.html'), name='public'),

    # auth urls
    url(r'^login/$', auth_views.login, {'template_name': u'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

]

faturamento/models.py
from django.db import models
from django.shortcuts import resolve_url





class BoletoAbstract(models.Model):
    nnum_bol = models.BigIntegerField('CODIGO BOLETO',db_column='NNum_Bol', primary_key=True)  # Field name made lowercase.
    data_bol = models.DateTimeField('DATA EMISSÃO',db_column='Data_Bol', blank=True, null=True)  # Field name made lowercase.
    venc_bol = models.DateTimeField('DATA VENCIMENTO',db_column='Venc_Bol', blank=True, null=True)  # Field name made lowercase.
    numdoc_bol = models.BigIntegerField('NFE ', db_column='NumDoc_Bol', blank=True, null=True)  # Field name made lowercase.
    val_bol = models.CharField('VALOR ', db_column='Val_Bol', max_length=53, blank=True, null=True)  # Field name made lowercase.
    sac_bol = models.CharField('CLIENTE', db_column='Sac_Bol', max_length=30, blank=True, null=True)  # Field name made lowercase.
    end_bol = models.CharField('ENDEREÇO',db_column='End_Bol', max_length=40, blank=True, null=True)  # Field name made lowercase.
    cep_bol = models.CharField('CEP',db_column='Cep_Bol', max_length=10, blank=True, null=True)  # Field name made lowercase.
    bair_bol = models.CharField('BAIRRO' ,db_column='Bair_Bol', max_length=12, blank=True, null=True)  # Field name made lowercase.
    cid_bol = models.CharField('CIDADE',db_column='Cid_Bol', max_length=15, blank=True, null=True)  # Field name made lowercase.
    uf_bol = models.CharField('ESTADO',db_column='UF_Bol', max_length=2, blank=True, null=True)  # Field name made lowercase.
    pes_bol = models.CharField('TIPO CLIENTE',db_column='Pes_Bol', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cnpj_bol = models.CharField('CNPJ',db_column='CNPJ_Bol', max_length=14, blank=True, null=True)  # Field name made lowercase.
    env_bol = models.NullBooleanField('ENVIADO',db_column='Env_Bol')  # Field name made lowercase.
    ind_tip_nfe_srv = models.NullBooleanField('SERVIÇO',db_column='IND_TIP_NFE_SRV')  # Field name made lowercase.

    class Meta:
        abstract = True
        verbose_name = 'Boleto'
        verbose_name_plural = 'Boletos'

    def __str__(self):
        return self.sac_bol

class BoletoData(BoletoAbstract):

    def get_absolute_url(self):
        return resolve_url('boletos:boleto_data_detail', nnum_bol=self.nnum_bol)

    class Meta:
        managed = False
        db_table = 'BOLETOS_DATA_NFE'

class BoletoMidia(BoletoAbstract):
    def get_absolute_url(self):
        return resolve_url('boletos:boleto_midia_detail', nnum_bol=self.nnum_bol)

    class Meta:
        managed = False
        db_table = 'BOLETOS_MIDIA_NFE'

class BoletoTech(BoletoAbstract):

    def get_absolute_url(self):
        return resolve_url('boletos:boleto_tech_detail', nnum_bol=self.nnum_bol)

    class Meta:
        managed = False
        db_table = 'BOLETOS_TECHCD_NFE'


class ItmNfeSaidaPagtoAbstract(models.Model):
    class Meta:
        abstract = True
        verbose_name = 'Item NFe Saida'
        verbose_name = 'Itens NFe Saida'

        unique_together = ('cod_nf_saida', 'datavencnf_saida_pagto')

    cod_nf_saida = models.BigIntegerField(db_column='COD_NF_SAIDA', primary_key=True)  # Field name made lowercase.
    parcnf_saida_pagto = models.DecimalField(db_column='PARCNF_SAIDA_PAGTO', max_digits=19, decimal_places=4)  # Field name made lowercase.
    cod_pagto = models.IntegerField(db_column='COD_PAGTO', blank=True, null=True)  # Field name made lowercase.
    cod_frmpagto = models.IntegerField(db_column='COD_FRMPAGTO', blank=True, null=True)  # Field name made lowercase.
    valnf_saida_pagto = models.DecimalField(db_column='VALNF_SAIDA_PAGTO', max_digits=19, decimal_places=4, blank=True, null=True)  # Field name made lowercase.
    realnf_saida_pagto = models.DecimalField(db_column='REALNF_SAIDA_PAGTO', max_digits=19, decimal_places=4, blank=True, null=True)  # Field name made lowercase.
    datavencnf_saida_pagto = models.DateTimeField(db_column='DATAVENCNF_SAIDA_PAGTO', blank=True, null=True)  # Field name made lowercase.
    dataquitnf_saida_pagto = models.DateTimeField(db_column='DATAQUITNF_SAIDA_PAGTO', blank=True, null=True)  # Field name made lowercase.
    quemquitnf_saida_pagto = models.CharField(db_column='QUEMQUITNF_SAIDA_PAGTO', max_length=30, blank=True, null=True)  # Field name made lowercase.
    cod2_pagto = models.BigIntegerField(db_column='COD2_PAGTO', blank=True, null=True)  # Field name made lowercase.
    cod2_frmpagto = models.BigIntegerField(db_column='COD2_FRMPAGTO', blank=True, null=True)  # Field name made lowercase.
    cod_banco = models.BigIntegerField(db_column='COD_BANCO', blank=True, null=True)  # Field name made lowercase.
    chqnf_saida_pagto = models.CharField(db_column='CHQNF_SAIDA_PAGTO', max_length=20, blank=True, null=True)  # Field name made lowercase.



    def __str__(self):
        return '{0} - {1} - {2}'.format(str(self.cod_nf_saida), str(self.datavencnf_saida_pagto), str(self.valnf_saida_pagto))




class ItemNfeSaidaPagtoTech(ItmNfeSaidaPagtoAbstract):

    class Meta:
        managed = False
        db_table =  'ITM_NFE_SAIDA_PAGTO'

class ItemNfeSaidaPagtoData(ItmNfeSaidaPagtoAbstract):

    class Meta:
        managed = False
        db_table =  'ITM_NFE_SAIDA_PAGTO_DATA'

class ItemNfeSaidaPagtoMidia(ItmNfeSaidaPagtoAbstract):

    class Meta:
        managed = False
        db_table =  'ITM_NFE_SAIDA_PAGTO_MIDIA'


class ItemNfeSaidaPagtoTechSRV(ItmNfeSaidaPagtoAbstract):
    class Meta:
        managed = False
        db_table = 'ITM_NFE_SAIDA_PAGTO_SRV'


class ItemNfeSaidaPagtoDataSRV(ItmNfeSaidaPagtoAbstract):
    class Meta:
        managed = False
        db_table = 'ITM_NFE_SAIDA_PAGTO_DATA_SRV'


class ItemNfeSaidaPagtoMidiaSRV(ItmNfeSaidaPagtoAbstract):
    class Meta:
        managed = False
        db_table = 'ITM_NFE_SAIDA_PAGTO_MIDIA_SRV'

faturamento/forms.py
from django import forms

from faturamento.models import BoletoTech, BoletoMidia, BoletoData


class BoletoTechForm(forms.ModelForm):
    empresa = forms.CharField(label='empresa',widget=forms.HiddenInput())
    class Meta:
        model = BoletoTech
        fields = ('nnum_bol', 'numdoc_bol', 'sac_bol', 'val_bol',
                  'data_bol', 'venc_bol', 'val_bol', 'empresa')


class BoletoMidiaForm(forms.ModelForm):
    empresa = forms.CharField(label='empresa', widget=forms.HiddenInput())
    class Meta:
        model = BoletoMidia
        fields = ('nnum_bol', 'numdoc_bol', 'sac_bol', 'val_bol',
                  'data_bol', 'venc_bol', 'val_bol')


class BoletoDataForm(forms.ModelForm):
    empresa = forms.CharField(label='empresa', widget=forms.HiddenInput())
    class Meta:
        model = BoletoData
        fields = ('nnum_bol', 'numdoc_bol', 'sac_bol', 'val_bol',
                  'data_bol', 'venc_bol', 'val_bol')

faturamento/views/views_boletos.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.db import transaction
from django.db.models import Q

from faturamento.forms import BoletoTechForm, BoletoDataForm, BoletoMidiaForm
from faturamento.models import BoletoData, BoletoMidia, BoletoTech, ItemNfeSaidaPagtoDataSRV, ItemNfeSaidaPagtoData, \
    ItemNfeSaidaPagtoMidiaSRV, ItemNfeSaidaPagtoMidia
from faturamento.models import ItemNfeSaidaPagtoTech, ItemNfeSaidaPagtoTechSRV


def get_boletos(request, empresa):
    if empresa == 'data':
        if request.GET.get('search') is not '':
            boleto_list = BoletoData.objects.using('techcd') \
                .filter(Q(numdoc_bol=request.GET.get('search'))).order_by('-nnum_bol')
        else:
            boleto_list = BoletoData.objects.using('techcd').order_by('-nnum_bol')[:10]

    elif empresa == 'midia':
        if request.GET.get('search') is not '':
            boleto_list = BoletoMidia.objects.using('techcd') \
                .filter(Q(numdoc_bol=request.GET.get('search'))).order_by('-nnum_bol')
        else:
            boleto_list = BoletoMidia.objects.using('techcd').order_by('-nnum_bol')[:10]

    else:
        if request.GET.get('search') is not '':
            boleto_list = BoletoTech.objects.using('techcd') \
                .filter(Q(numdoc_bol=request.GET.get('search'))).order_by('-nnum_bol')
        else:
            boleto_list = BoletoTech.objects.using('techcd').order_by('-nnum_bol')[:10]

    return boleto_list


def boleto_list(request):
    template = 'faturamento/boletos_list.html'
    empresa = request.GET.get('radio-empresa')

    boleto_list = get_boletos(request, empresa)

    context = {'boletos': boleto_list, 'empresa': empresa}
    return render(request, template, context)


def boleto_tech_detail(request, nnum_bol):
    boleto = get_object_or_404(BoletoTech.objects.using('techcd'), nnum_bol=nnum_bol)
    form = BoletoTechForm(instance=boleto)
    return render(request, 'faturamento/boleto.html', {'form': form, 'empresa': 'TechCD'})


def boleto_data_detail(request, nnum_bol):
    boleto = get_object_or_404(BoletoData.objects.using('techcd'), nnum_bol=nnum_bol)
    form = BoletoDataForm(instance=boleto)
    return render(request, 'faturamento/boleto.html', {'form': form, 'empresa': 'Data Store'})


def boleto_midia_detail(request, nnum_bol):
    boleto = get_object_or_404(BoletoMidia.objects.using('techcd'), nnum_bol=nnum_bol)
    form = BoletoMidiaForm(instance=boleto)
    return render(request, 'faturamento/boleto.html', {'form': form, 'empresa': 'Midia Center'})


def boleto_update(request, nnum_bol):
    if request.POST:
        empresa = request.POST.get('empresa')
        # verifica de qual empresa é para montar o form
        if empresa == 'TechCD':
            boleto = get_object_or_404(BoletoTech.objects.using('techcd'), nnum_bol=nnum_bol)
            form = BoletoTechForm(request.POST, instance=boleto)
            if boleto.ind_tip_nfe_srv:
                item_pag = get_object_or_404(ItemNfeSaidaPagtoTechSRV.objects.using('techcd'),
                                             cod_nf_saida=boleto.numdoc_bol, datavencnf_saida_pagto=boleto.venc_bol)
            else:

                item_pag = get_object_or_404(ItemNfeSaidaPagtoTech.objects.using('techcd'),
                                             cod_nf_saida=boleto.numdoc_bol, datavencnf_saida_pagto=boleto.venc_bol)


        elif empresa == 'Data Store':
            boleto = get_object_or_404(BoletoData.objects.using('techcd'), nnum_bol=nnum_bol)
            form = BoletoDataForm(request.POST, instance=boleto)
            if boleto.ind_tip_nfe_srv:
                item_pag = get_object_or_404(ItemNfeSaidaPagtoDataSRV.objects.using('techcd'),
                                             cod_nf_saida=boleto.numdoc_bol, datavencnf_saida_pagto=boleto.venc_bol)
            else:

                item_pag = get_object_or_404(ItemNfeSaidaPagtoData.objects.using('techcd'),
                                             cod_nf_saida=boleto.numdoc_bol, datavencnf_saida_pagto=boleto.venc_bol)
        else:
            boleto = get_object_or_404(BoletoMidia.objects.using('techcd'), nnum_bol=nnum_bol)
            form = BoletoDataForm(request.POST, instance=boleto)
            if boleto.ind_tip_nfe_srv:
                item_pag = get_object_or_404(ItemNfeSaidaPagtoMidiaSRV.objects.using('techcd'),
                                             cod_nf_saida=boleto.numdoc_bol, datavencnf_saida_pagto=boleto.venc_bol)
            else:

                item_pag = get_object_or_404(ItemNfeSaidaPagtoMidia.objects.using('techcd'),
                                             cod_nf_saida=boleto.numdoc_bol, datavencnf_saida_pagto=boleto.venc_bol)

                # salva o boleto
        if form.is_valid():
            bol = form.save()

            _instance = type(item_pag)
            _instance.objects.using('techcd'). \
                filter(Q(cod_nf_saida=item_pag.cod_nf_saida) &
                       Q(datavencnf_saida_pagto=item_pag.datavencnf_saida_pagto)). \
                update(datavencnf_saida_pagto=bol.venc_bol, valnf_saida_pagto=bol.val_bol)
            messages.success(request, 'NFe {0}  da  {1}  Alterada  com Sucesso!'.format(boleto.numdoc_bol, empresa))
        else:
            form = BoletoTechForm(request.POST)

    return render(request, 'faturamento/boleto.html', {'form': form})

faturamento/templates/faturamento/boleto.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content%}
<div class="moda-dialog">
    <div class="modal-content">
        <form  action="{% url 'boletos:boleto_update' form.instance.nnum_bol %}" method="post"
               class="js-form-update-boleto" data-toggle="validator">
            {% csrf_token %}

            <div class="modal-header">
                <button class="close" data-dismiss="modal"
                        onclick="window.history.back()" type="button">&times</button>
                <h3 class="help-block"> Boleto <strong>{{ empresa }}</strong></h3>
                {% render_field form.empresa  value=empresa %}
            </div><!-- modal-header -->

            <div class="modal-body">

                {% if messages %}

                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button class="close" data-dismiss="alert" type="button" aria-label="fechar">
                        <span aria-hidden="true" >&times;</span>
                    </button>

                    {{ message }}
                </div>
                {% endfor %}

                {% endif %}


                <div class="row">

                    <div class="col-md-2" >
                        <div class="form-group {% if form.nnum_bol.errors %} has-error {% endif %}">
                            <label for="{{ form.nnum_bol.id_for_label }}">{{ form.nnum_bol.label_tag }}</label>
                            {% render_field form.nnum_bol  class="form-control"  disabled="True" %}
                            {% for error in form.nnum_bol.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div> <!--  numm_bol -->

                    <div class="col-md-2">
                        <div class="form-group {% if form.numdoc_bol.errors %} has-error {% endif %}">
                            <label for="{{ form.numdoc_bol.id_for_label }}">{{ form.numdoc_bol.label_tag }}</label>
                            {% render_field form.numdoc_bol class="form-control" disabled="True" %}
                            {% for error in form.numdoc_bol.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div><!--  numdoc_bol -->
                    </div>

                    <div class="col-md-12">
                        <div class="form-group {% if form.numdoc_bol.errors %} has-error {% endif %}">
                            <label for="{{ form.sac_bol.id_for_label }}"> {{ form.sac_bol.label_tag }}</label>
                            {% render_field form.sac_bol class="form-control" disabled="True" %}
                            {% for error in form.sac_bol.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div> <!--  sacado -->

                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="{{ form.data_bol.id_for_label }}">{{ form.data_bol.label_tag }}</label>
                            {% render_field form.data_bol class="form-control calender" disabled="True" %}
                            {% for error in form.data_bol.errors %}
                            <span class="help-block"> {{ error }}</span>
                            {% endfor %}
                        </div>
                    </div><!-- data de emissao -->

                    <div class="col-md-2">
                        <div class="form-group {% if form.venc_bol.errors %} has-error {% endif %}">
                            <label for="{{ form.venc_bol.id_for_label }}">{{ form.venc_bol.label_tag }}</label>
                            {% render_field form.venc_bol class="form-control calender" %}
                            {%for error in form.venc_bol.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div><!--  vencimento -->

                    <div class="col-md-2">
                        <div class="form-group {% if form.val_bol.errors %} has-error {% endif %}">
                            <label for="{{ form.val_bol.id_for_label }}">{{ form.val_bol.label_tag }}</label>
                            {% render_field form.val_bol class="form-control" pattern="^\d+(?:\.\d{1,2})?$" title="Campo decimal , exemplo 0.00 , utiliza somente ponto para as casas decimais" %}
                            {%for error in form.val_bol.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div><!--  vencimento -->


                </div><!--  row -->
            </div><!-- modal-body -->

            <div class="modal-footer">
                <button class="btn btn-primary " onclick="window.history.back()"
                        type="button"> voltar </button>

                <button class="btn btn-warning" type="submit" >
                    Alterar
                </button>

            </div><!-- modal-footer -->
        </form><!-- fomulario -->
    </div><!-- modal-content -->
</div><!-- modal-dialog -->





{% endblock %}

{% block js_extra %}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/locales/bootstrap-datepicker.pt-BR.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrapValidator.js' %}"></script>
<script  src="{% static 'js/jquery.bsFormAlerts.js' %}"></script>
<script type="text/javascript" src="{% static 'js/apps.js' %}"></script>
{% endblock %}

faturamento/templates/faturamento/boletos_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<h1 class="page-header">Boletos</h1>

<div class="row">

    <form action="" method="GET" >
        {% csrf_token %}


        <div class="form-group">
            <div class="row">

                <div class="col-md-6">
                    <div class="input-group">

                        <input id="table-input" name="search" type="Search" placeholder="Pesquisar ..."
                               class="form-control" onkeypress="searchTable()"
                               pattern="[0-9]*" required
                               title="Há! esse campo so aceita numeros, Digite o numero da NFE relacionada ao Boleto"/>

                        <div class="input-group-btn">
                            <button class="btn btn-success" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </div>
                    </div>
                </div><!-- input de busca -->


                <div class="pull-right col-md-4">


                    <div class="radio-inline">
                        <label><input type="radio" name="radio-empresa"
                                      {% if empresa == 'tech' %} checked {% endif %}
                                      value="tech" required>TechCD</label>
                    </div>

                    <div class="radio-inline">
                        <label><input type="radio" name="radio-empresa"
                                        {% if empresa == 'data' %} checked {% endif %}
                                      value="data">Data Store</label>
                    </div>

                    <div class="radio-inline">
                        <label><input type="radio" name="radio-empresa"
                                        {% if empresa == 'midia' %} checked {% endif %}
                                      value="midia">Midia Center</label>
                    </div>

                </div><!-- radios options-->


            </div><!-- row -->
        </div><!-- form-group -->
    </form><!-- form -->
</div><!-- row -->

<div class="row" style="">

    <table id="table-contact" class="table table-striped table-hover table-sm">
        <thead class="thead-inverse">
        <tr>
            <th colspan="4"></th>
        </tr>
        <tr class="bg-success">
            <th>#</th>
            <th>DOCUMENTO</th>
            <th>CLIENTE </th>
            <th>Vencimeto</th>
            <th>Valor</th>
            <th>Editar</th>
        </tr>
        </thead>

        <tbody>
        {% for boleto in boletos %}
        <tr>
            <th scope="row">{{ boleto.nnum_bol }}</th>
            <td>{{ boleto.numdoc_bol }}</td>
            <td>{{ boleto.sac_bol }}</td>
            <td>{{ boleto.venc_bol |date:"d/m/y"}}</td>
            <td>{{ boleto.val_bol}}</td>
            <td>
                <a href="{{ boleto.get_absolute_url }}" role="button" class="btn btn-small btn-warning">
                    Editar
                </a>
            </td>
        </tr>

        {% empty %}
        <tr>
            <th colspan="6" class="bg-warning text-center"> Não foi encontrado nenhum resultado</th>
        </tr>

        {% endfor %}
        </tbody>
    </table>

    {% if boletos.has_other_pages %}
    <ul class="pagination">
        {% if boletos.has_previous %}
        <li><a href="?page={{ boletos.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in boletos.paginator.page_range %}
        {% if boletos.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if boletos.has_next %}
        <li><a href="?page={{ boletos.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}

</div>



{% endblock %}

{% block js_extra %}
<!-- JQUERY EXTRAR PARA TABELAS PLUGIN https://datatables.net/-->
<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/locales/bootstrap-datepicker.pt-BR.js' %}"></script>
<script  src="{% static 'js/jquery.bsFormAlerts.js' %}"></script>
<script type="text/javascript" src="{% static 'js/apps.js' %}"></script>
<script>

function searchTable() {
  // Declare variables
   var input, filter, table, tr, td, i;
    input = document.getElementById("table-input");
    filter = input.value.toUpperCase();
    table = document.getElementById("table-contact");
    tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

{% endblock %}